name: ci
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      - "dev"
      - "main"
      - "feature/github-actions"
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/architec-ton/wallet-tma:${{ github.sha }}
            ghcr.io/architec-ton/wallet-tma:latest
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: ./Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
